using System;
using System.Collections.Generic;
using System.Text;

namespace Denomica.Cosmos.Extensions.JsonLd.Model
{
    /// <summary>
    /// Represents a vector embedding generated by a vector embedding model.
    /// </summary>
    public class VectorEmbedding
    {
        /// <summary>
        /// Gets or sets the vector represented as an array of single-precision floating-point values.
        /// </summary>
        public float[] Vector { get; set; } = Array.Empty<float>();

        /// <summary>
        /// Gets or sets the total number of tokens consumed generating the embedding vector.
        /// </summary>
        public int TotalTokens { get; set; }

        /// <summary>
        /// Gets or sets the name of the model used to generate the embedding vector.
        /// </summary>
        public string Model { get; set; } = string.Empty;
    }
}
